version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
      - mongo
      - identity-service
      - post-service
      - media-service
      - search-service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - MEDIA_SERVICE_URL=${MEDIA_SERVICE_URL}
      - SEARCH_SERVICE_URL=${SEARCH_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservices-net

  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    networks:
      - microservices-net

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - microservices-net

  media-service:
    build: ./media-service
    container_name: media-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - cloud_name=${cloud_name}
      - api_key=${api_key}
      - api_secret=${api_secret}
    networks:
      - microservices-net

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "3004:3004"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    networks:
      - microservices-net

volumes:
  mongo_data:

networks:
  microservices-net:
    driver: bridge
